### ISSUE TITLE
How to actually use? (not duplicate)

### ISSUE THREAD

**Issue by Apppppppple** [fossephate/JoyCon-Driver#121]
I have the controllers connected, and Mario theme and gyro works fine. However, I cannot figure out how to use this with a game. (The game is ssf2: [https://www.mcleodgaming.com/games/ssf2/downloads](https://www.mcleodgaming.com/games/ssf2/downloads)(the controller compatibility is not enabled in browser))
On Windows 10  Intel Pretty sure I'm 64 bit (x86)
P.S. Sorry if this post looks horrible.
Edit: Also, I do not see anything in Vjoy monitor

**Comment by Variable-X** [comment]
Also, fairly sure it is not combining l and r joy cons right

**Comment by Variable-X** [comment]
Do I need UCR?

**Comment by Aidoboy** [comment]
>(the controller compatibility is not enabled in browser)

Pretty much wrecks everything here.

**Comment by Variable-X** [comment]
I know but the downloaded version allows controllers.

**Comment by Variable-X** [comment]
My question wasn't about that specific game, just in general

**Comment by Variable-X** [comment]
My question wasn't about that specific game, just in general. Also, the downloaded version supports controllers, but not combined ones.

**Comment by Aidoboy** [comment]
Did you possibly forget to check the "Combine JoyCons" box?

**Comment by Variable-X** [comment]
No

**Comment by Aidoboy** [comment]
Did you set VJoy to 32 buttons?

**Comment by Variable-X** [comment]
Yes

**Comment by Aidoboy** [comment]
I don't know then, sorry.

**Comment by Variable-X** [comment]
Thanks. Have you gotten it working for any of your games? I'm pretty sure I just don't know how to integrate it with a game.
